# Generated by Django 5.2.4 on 2025-07-10 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0010_alter_newssentimentdata_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sentiment_analysis_text', models.TextField(blank=True, null=True)),
                ('technical_analysis_text', models.TextField(blank=True, null=True)),
                ('strategy_analysis_text', models.TextField(blank=True, null=True)),
                ('classification', models.IntegerField(choices=[(0, 'Down'), (1, 'Up')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.coin')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='analysis_fu_symbol__d57add_idx')],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='SentimentFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_num_articles_ma1_10', models.FloatField(null=True)),
                ('prev_extremely_positive_count_ma1_5', models.FloatField(null=True)),
                ('prev_avg_sentiment_std1_6_ma', models.FloatField(null=True)),
                ('prev_extremely_positive_count_ma1_4', models.FloatField(null=True)),
                ('prev_extremely_negative_count_lag5', models.FloatField(null=True)),
                ('avg_sentiment_news_prev_std5_ma', models.FloatField(null=True)),
                ('change_pct', models.FloatField(db_column='2_periods_back_back_change_pct', null=True)),
                ('change_pct_lag1', models.FloatField(db_column='2_periods_back_back_change_pct_lag1', null=True)),
                ('change_pct_lag4', models.FloatField(db_column='2_periods_back_back_change_pct_lag4', null=True)),
                ('change_pct_lag8', models.FloatField(db_column='2_periods_back_back_change_pct_lag8', null=True)),
                ('prev_avg_sentiment_lag4', models.FloatField(null=True)),
                ('prev_min_sentiment_lag10', models.FloatField(null=True)),
                ('prev_std_sentiment_lag1', models.FloatField(null=True)),
                ('prev_min_sentiment_lag1', models.FloatField(null=True)),
                ('prev_std_sentiment_lag3', models.FloatField(null=True)),
                ('prev_median_sentiment_lag8', models.FloatField(null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_features', to='analytics.coin')),
                ('timestamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_features', to='analytics.newssentimentdata')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='analysis_se_symbol__fefba0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TechnicalFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_atr_lag9', models.FloatField(null=True)),
                ('prev_macd_signal_lag4', models.FloatField(null=True)),
                ('prev_rsi_ma5', models.FloatField(null=True)),
                ('prev_bb_lower_lag10', models.FloatField(null=True)),
                ('prev_quote_volume_ma8', models.FloatField(null=True)),
                ('prev_macd_hist_std8_ma', models.FloatField(null=True)),
                ('prev_williams_r_ma7', models.FloatField(null=True)),
                ('volume_prev_ma10', models.FloatField(null=True)),
                ('prev_quote_volume_ma7', models.FloatField(null=True)),
                ('prev_close_ma5', models.FloatField(null=True)),
                ('prev_macd_hist_std7_ma', models.FloatField(null=True)),
                ('prev_taker_buy_base_volume_std7_ma', models.FloatField(null=True)),
                ('prev_rsi_std2_ma', models.FloatField(null=True)),
                ('prev_taker_buy_quote_volume_lag10', models.FloatField(null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_features', to='analytics.coin')),
                ('timestamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_features', to='analytics.marketdata')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='analysis_te_symbol__3e4d3d_idx')],
            },
        ),
    ]
