# Generated by Django 5.2.4 on 2025-07-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullanalysis',
            name='created_at',
        ),
    ]
