# Generated by Django 5.2.4 on 2025-08-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_fullanalysis_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalfeatures',
            name='record_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
