# Generated by Django 5.2.4 on 2025-08-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_technicalfeatures_record_timestamp'),
        ('analytics', '0013_dailysentimentdata_bearish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentfeatures',
            name='change_pct',
        ),
        migrations.RemoveField(
            model_name='sentimentfeatures',
            name='change_pct_lag1',
        ),
        migrations.RemoveField(
            model_name='sentimentfeatures',
            name='change_pct_lag4',
        ),
        migrations.RemoveField(
            model_name='sentimentfeatures',
            name='change_pct_lag8',
        ),
        migrations.AddField(
            model_name='sentimentfeatures',
            name='record_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='technicalfeatures',
            name='change_pct',
            field=models.FloatField(db_column='2_periods_back_back_change_pct', null=True),
        ),
        migrations.AddField(
            model_name='technicalfeatures',
            name='change_pct_lag1',
            field=models.FloatField(db_column='2_periods_back_back_change_pct_lag1', null=True),
        ),
        migrations.AddField(
            model_name='technicalfeatures',
            name='change_pct_lag4',
            field=models.FloatField(db_column='2_periods_back_back_change_pct_lag4', null=True),
        ),
        migrations.AddField(
            model_name='technicalfeatures',
            name='change_pct_lag8',
            field=models.FloatField(db_column='2_periods_back_back_change_pct_lag8', null=True),
        ),
        migrations.AlterField(
            model_name='sentimentfeatures',
            name='timestamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_features', to='analytics.marketdata'),
        ),
    ]
