# Generated by Django 5.2.4 on 2025-08-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_remove_sentimentfeatures_change_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentfeatures',
            name='prev_extremely_negative_count_std1_9_ma',
            field=models.FloatField(null=True),
        ),
    ]
