# Generated by Django 4.2.23 on 2025-06-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('SOL', 'Solana'), ('XRP', 'XRP'), ('USDC', 'USD Coin'), ('LTC', 'Litecoin'), ('USD', 'US Dollar')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('decimal_places', models.IntegerField(default=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=32)),
                ('quote_volume', models.DecimalField(decimal_places=8, max_digits=32)),
                ('num_trades', models.PositiveIntegerField()),
                ('taker_buy_base_volume', models.DecimalField(decimal_places=8, default=0, max_digits=32, null=True)),
                ('taker_buy_quote_volume', models.DecimalField(decimal_places=8, default=0, max_digits=32, null=True)),
                ('price_change_percent_24h', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('rsi', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('macd', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('macd_signal', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('macd_hist', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('bb_upper', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('bb_middle', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('bb_lower', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='analytics.coin')),
            ],
            options={
                'ordering': ['-close_time'],
                'indexes': [models.Index(fields=['symbol', 'close_time'], name='analytics_m_symbol__9b2de6_idx'), models.Index(fields=['close_time'], name='analytics_m_close_t_d621ff_idx')],
                'unique_together': {('symbol', 'close_time')},
            },
        ),
    ]
