# Generated by Django 4.2.6 on 2025-06-30 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='decimal_places',
        ),
    ]
