# Generated by Django 5.2.4 on 2025-07-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_coin_decimal_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdata',
            name='atr',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
    ]
