# Generated by Django 5.2.4 on 2025-07-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_marketdata_atr'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdata',
            name='williams_r',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
