# Generated by Django 5.2.4 on 2025-07-06 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_marketdata_williams_r'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSentimentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('title', models.TextField()),
                ('url', models.URLField()),
                ('sentiment_score', models.FloatField()),
                ('sentiment_label', models.CharField(max_length=30)),
                ('confidence_score', models.FloatField(null=True)),
                ('summary', models.TextField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.coin')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='analytics_n_symbol__c61e3f_idx')],
            },
        ),
    ]
