# Generated by Django 5.2.4 on 2025-07-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_newssentimentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssentimentdata',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
