# Generated by Django 5.2.4 on 2025-07-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_newssentimentdata_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newssentimentdata',
            old_name='id',
            new_name='article_id',
        ),
    ]
