# Generated by Django 5.2.4 on 2025-07-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_rename_id_newssentimentdata_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssentimentdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newssentimentdata',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
