# Generated by Django 5.2.4 on 2025-07-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_alter_newssentimentdata_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssentimentdata',
            name='sentiment_score',
            field=models.FloatField(null=True),
        ),
    ]
