# Generated by Django 5.2.4 on 2025-07-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_newssentimentdata_sentiment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssentimentdata',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newssentimentdata',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
