# Generated by Django 5.2.4 on 2025-07-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_newssentimentdata_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySentimentData',
            fields=[
                ('article_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('sentiment_score', models.FloatField(null=True)),
                ('sentiment_label', models.CharField(max_length=30)),
                ('confidence_score', models.FloatField(null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.coin')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='analytics_d_symbol__f6334f_idx')],
            },
        ),
    ]
