# Generated by Django 5.2.4 on 2025-07-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_dailysentimentdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysentimentdata',
            name='article_id',
        ),
        migrations.AddField(
            model_name='dailysentimentdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
