# Generated by Django 5.2.4 on 2025-07-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_remove_dailysentimentdata_article_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysentimentdata',
            name='bearish',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='dailysentimentdata',
            name='bullish',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='dailysentimentdata',
            name='extremely_bearish',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='dailysentimentdata',
            name='extremely_bullish',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='dailysentimentdata',
            name='neutral',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
