# Generated by Django 5.2.5 on 2025-08-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_dailysentimentdata_bearish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssentimentdata',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
