# Generated by Django 5.2.5 on 2025-08-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_alter_newssentimentdata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssentimentdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
