# Generated by Django 5.2.5 on 2025-08-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_alter_newssentimentdata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssentimentdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newssentimentdata',
            name='article_id',
            field=models.CharField(max_length=100),
        ),
    ]
