# Generated by Django 5.2.5 on 2025-08-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_newssentimentdata_id_and_more'),
        ('analytics', '0017_auto_20250810_2032'),
    ]

    operations = [
    ]
